FROM ubuntu:22.04
ENV     DEBIAN_FRONTEND noninteractive
RUN     sed -i 's/archive.ubuntu/mirrors.tencent/g' /etc/apt/sources.list && \
	    apt-get update && apt-get -y upgrade

RUN    	DEBIAN_FRONTEND=noninteractive  apt-get -y install --no-install-recommends  tzdata && dpkg-reconfigure -f noninteractive tzdata
RUN    	DEBIAN_FRONTEND=noninteractive  apt-get -y install --no-install-recommends  iputils-ping 
RUN    	DEBIAN_FRONTEND=noninteractive  apt-get -y install --no-install-recommends  make 
RUN    	DEBIAN_FRONTEND=noninteractive  apt-get -y install --no-install-recommends  build-essential 
RUN    	DEBIAN_FRONTEND=noninteractive  apt-get -y install --no-install-recommends  flex 
RUN    	DEBIAN_FRONTEND=noninteractive  apt-get -y install --no-install-recommends  gcc 
RUN    	DEBIAN_FRONTEND=noninteractive  apt-get -y install --no-install-recommends  g++ 
RUN    	DEBIAN_FRONTEND=noninteractive  apt-get -y install --no-install-recommends  iptables 
RUN    	DEBIAN_FRONTEND=noninteractive  apt-get -y install --no-install-recommends  python3 
RUN    	DEBIAN_FRONTEND=noninteractive  apt-get -y install --no-install-recommends  openjdk-17-jdk 
RUN    	DEBIAN_FRONTEND=noninteractive  apt-get -y install --no-install-recommends  fp-compiler 
# RUN    	DEBIAN_FRONTEND=noninteractive  apt-get -y install --no-install-recommends  mono-devel 
RUN    	DEBIAN_FRONTEND=noninteractive  apt-get -y install --no-install-recommends  busybox 
RUN    	DEBIAN_FRONTEND=noninteractive  apt-get -y install --no-install-recommends  dos2unix 
RUN    	DEBIAN_FRONTEND=noninteractive  apt-get -y install --no-install-recommends  wget 
RUN    	DEBIAN_FRONTEND=noninteractive  apt-get -y install --no-install-recommends  sqlite3 
# add golang support
RUN    	DEBIAN_FRONTEND=noninteractive  apt-get -y install --no-install-recommends  golang-1.13
RUN 	ln -s /usr/lib/go-1.13/bin/go /usr/bin/
# install debian package of similarity-tester
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends similarity-tester
RUN cp /usr/bin/sim_c++ /usr/bin/sim_cc
# make Chinese Character works in Docker
RUN apt-get install -y locales locales-all
RUN locale-gen zh_CN.UTF-8 && dpkg-reconfigure locales && /usr/sbin/update-locale LANG=zh_CN.UTF-8
ENV LANG zh_CN.UTF-8  
ENV LANGUAGE zh_CN:zh  
ENV LC_ALL zh_CN.UTF-8 
# java modify
RUN echo "/usr/lib/jvm/java-17-openjdk-amd64/lib" >> /etc/ld.so.conf.d/java.conf && \
    echo "/usr/lib/jvm/java-17-openjdk-amd64/lib/jli" >> /etc/ld.so.conf.d/java.conf && \
    ldconfig
